AWSTemplateFormatVersion: '2010-09-09'
Description: Splunk Enterprise EC2 Setup on Amazon Linux 2023 (Ohio Region)

Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access
    Type: AWS::EC2::KeyPair::KeyName

Resources:
  SplunkSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and Splunk access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8000
          ToPort: 8000
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8089
          ToPort: 8089
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 9997
          ToPort: 9997
          CidrIp: 0.0.0.0/0

  SplunkInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: c7i-flex.large
      ImageId: ami-06d4b7182ac3480fa
      SecurityGroups:
        - Ref: SplunkSecurityGroup
      KeyName: 
        Ref: KeyName
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 20
            VolumeType: gp3
            DeleteOnTermination: true
Outputs:
  InstancePublicIP:
    Description: Public IP of the Splunk EC2 instance
    Value:
      Fn::GetAtt:
        - SplunkInstance
        - PublicIp
